name: Build & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: src/front

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest
    
    - name: Install NPM packages
      run: npm ci
    
    - name: Build project
      run: CI=false npm run build
    
    # - name: Run tests
    #   run: npm run test
    # - name: TEST
    #   run: |
    #     ls -R
    - name: Commit documentation changes
      run: |
        git clone https://github.com/malago86/predicateTrees.git --branch gh-pages --single-branch gh-pages
        cp -r src/front/build/* gh-pages/ 
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}